name: Penetration test request
description: Request a manual penetration test of your product/functionality
labels: ["team/security", "status/draft"]
body:          
  - type: input
    id: productteam
    attributes:
      label: Product team
      description: The product team who owns the product/functionality to be tested
    validations:
      required: true

  - type: textarea
    id: in-scope
    attributes:
      label: In scope
      description: What functionality should be penetration tested?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Test environment
      description: In what test environment should the test be run?

  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: When should this test be conducted?
      
  - type: input
    id: contactperson
    attributes:
      label: Contact person
      description: Who should the security team get in touch with to coordinate the test?

  - type: markdown
    attributes:
      value: |
        * Bullet 1
        * Bullet 2
