name: Penetration test request
description: Request a manual penetration test of your product/functionality
labels: ["team/security", "status/draft"]
body:
  - type: markdown
    attributes:
      value: |
        * The product/functionality to be must be stable and deployed to a test environment prior to the test
        * Team security will collect penetration test requests and engage external penetration testers to perform tests in bulk
        * Team security will coordinate the penetration tests and collect findings
        * The product team will name one team member to be point of contact for clarifications and coordination activities
        * Penetration tests may be re-run after fixes have been implemented
        
  - type: input
    id: productteam
    attributes:
      label: Product team
      description: Which product team owns the product/functionality to be tested?
    validations:
      required: true

  - type: textarea
    id: in-scope
    attributes:
      label: In scope - functionality to be tested
      description: Please give a high level description of the functionality to be penetration tested.
    validations:
      required: true

  - type: input
    id: epic
    attributes:
      label: Epic link
      description: Please enter link to the epic that covers the functionality to be penetration tested.

  - type: input
    id: environment
    attributes:
      label: Test environment
      description: In what test environment should the test be run?

  - type: textarea
    id: entrypoints
    attributes:
      label: API endpoints / GUI reference
      description: What are the entry points (API endpoints or starting point for GUI tests)?
    validations:
      required: true

  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: When should this test be conducted?
      
  - type: input
    id: contactperson
    attributes:
      label: Contact person
      description: Who should the security team get in touch with to coordinate the test?
